djangotweet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('tweetapp.urls')),
    path("",include('django.contrib.auth.urls'))
]

tweetapp/urls.py
from django.urls import path
from . import views

app_name = 'tweetapp'

urlpatterns = [
    path('',views.listtweet,name='listtweet'),    #gokalppo.com/tweetapp
    path('addtweet/',views.addtweet,name='addtweet'),   #gokalppo.com/tweetapp/addtweet
    path('addtweetbyform',views.addtweetbyform,name='addtweetbyform'),  #gokalppo.com/tweetapp/addtweetbyform
    path('addtweetbymodelform',views.addtweetbymodelform,name='addtweetbymodelform'),
    path('signup/',views.SignUpView.as_view(),name="signup"),
    path("deletetweet/<int:id>",views.deletetweet,name="deletetweet")
]

tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tweet(models.Model):
    username = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    message = models.CharField(max_length=150)

    def __str__(self):
        return f"Tweet User: {self.username} Message: {self.message}"

tweetapp/forms.py
from django import forms
from django.forms import ModelForm
from tweetapp.models import Tweet

class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(label="Nickname",max_length=50)
    message_input = forms.CharField(label="Message",max_length=100,
                                    widget=forms.Textarea(attrs={"class":"tweetmessage"}))
    


class AddTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ["username","message"]

tweetapp/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse, reverse_lazy
from tweetapp.forms import AddTweetForm, AddTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView


def listtweet(request):
    all_tweets = models.Tweet.objects.all()
    tweet_dict = {"tweets":all_tweets}
    return render(request,'tweetapp/listtweet.html',context=tweet_dict)

@login_required(login_url="/login")
def addtweet(request):
    if request.POST:
        message = request.POST["message"]
        models.Tweet.objects.create(username=request.user, message=message)
        return redirect(reverse('tweetapp:listtweet'))
    else:
        return render(request,'tweetapp/addtweet.html')
    


def addtweetbyform(request):
    if request.method == "POST":
        form = AddTweetForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname_input"]
            message = form.cleaned_data["message_input"]
            models.Tweet.objects.create(nickname=nickname, message=message)
            return redirect(reverse('tweetapp:listtweet'))
        else:
            print("error in form!")
            return render(request,'tweetapp/addtweetbyform.html', context={"form":form})
    else:
        form = AddTweetForm()
        return render(request,'tweetapp/addtweetbyform.html', context={"form":form})
    

def addtweetbymodelform(request):
    if request.method == "POST":
        form = AddTweetModelForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname"]
            message = form.cleaned_data["message"]
            models.Tweet.objects.create(nickname=nickname, message=message)
            return redirect(reverse('tweetapp:listtweet'))
        else:
            print("error in form!")
            return render(request,'tweetapp/addtweetbymodelform.html', context={"form":form})
    else:
        form = AddTweetModelForm()
        return render(request,'tweetapp/addtweetbymodelform.html', context={"form":form})



@login_required   
def deletetweet(request,id):
    tweet = models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect('tweetapp:listtweet')



class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

templates/base.html
{%load static%}

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <title>Anonymous Tweet App</title>
  <link rel="stylesheet" href="{% static 'tweetapp/customform.css' %}">

</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'tweetapp:listtweet' %}">Anonymous Tweet App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'tweetapp:listtweet' %}">List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tweetapp:addtweet' %}">Add Tweet</a>
          </li>
          <!--
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweetbyform' %}">Add Tweet By Form</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweetbymodelform' %}">Add Tweet By Model Form</a>
              </li>
            -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <form method="POST" action="{% url 'logout' %}?next=/" >
            {%csrf_token%}
            <button type="submit" class="nav-link btn btn-link">Logout</button>
          </form>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tweetapp:signup' %}">Signup</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>





  {%block content%}



  {%endblock%}
</body>

</html>

tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{%block content%}

<form action="" method="POST">
    {% csrf_token %}
    <div class="container" style="width: 50%;">
      <!--
    <div class="mb-3">
      <label for="nickname" class="form-label">Nickname</label>
      <input name="nickname" type="text" class="form-control" id="nickname">
    </div>
    -->
    <div class="mb-3">
      <label for="message" class="form-label">Message</label>
      <input name="message" type="text" class="form-control" id="message">
    </div>
    <button type="submit" class="btn btn-primary">Send Tweet</button>
  </div>
  </form>


{%endblock%}

tweetapp/templates/tweetapp/addtweetbyform.html
{% extends "base.html" %}
{% load static %}

{%block content%}
<h1>AddTweetByForm Page</h1>
<div class="container tweetform">
    <form action="" method="POST">
        {% csrf_token %}

        {%for field in form%}
        <div class="mb-3">
            {{field.label_tag}}
            {{field}}

        </div>
        {%endfor%}
        <button type="submit" class="btn btn-primary">Send Tweet</button>
    </form>
</div>

{%endblock%}

tweetapp/templates/tweetapp/addtweetbymodelform.html
{% extends "base.html" %}
{% load static %}

{%block content%}
<h1>AddTweetByModelForm Page</h1>
<div class="container tweetform">
    <form action="" method="POST">
        {% csrf_token %}

        {%for field in form%}
        <div class="mb-3">
            {{field.label_tag}}
            {{field}}

        </div>
        {%endfor%}
        <button type="submit" class="btn btn-primary">Send Tweet</button>
    </form>
</div>

{%endblock%}

tweetapp/templates/tweetapp/listtweet.html
{% extends "base.html" %}

{%block content%}


    <div class="container" style="width: 50%;">
        {%for tweet in tweets%}
        <div class="card" style="padding: 10px;">
           <div class="card-header" style="background-color: cornflowerblue;">
            <h4>{{tweet.username}}</h4>
           </div>
           <div class="card-body">
            <p class="card-text">{{tweet.message}}</p>
           </div>
           {%if tweet.username == user%}
            <a href="{% url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a>
           {%endif%}
        </div>
            {%endfor%}
      


</div>
{%endblock%}